# Identification du projet
sonar.projectKey=jenkins-portfolio
sonar.projectName=Jenkins Portfolio
sonar.projectVersion=1.0

# Sources à analyser
sonar.sources=src,backend

# Fichiers à exclure
sonar.exclusions=backend/node_modules/**,node_modules/**,public/**

# ✅ URL de ton SonarQube LOCAL (important !)
sonar.host.url=http://localhost:9000

# Ton token généré sur localhost:9000
sonar.token=squ_453468b2941d400d1d29b6784eb0309f13954da2

sonar.sourceEncoding=UTF-8