apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: portfolio
type: Opaque
data:
  # echo -n "admin" | base64
  username: YWRtaW4=
  # echo -n "Portfolio2025!" | base64
  password: UG9ydGZvbGlvMjAyNSE=